-- ============================================================
-- FreeAIHub — Seed Data (40 categories, 50 tools)
-- Run AFTER schema.sql in Supabase SQL Editor
-- ============================================================

-- ── ALL 40 CATEGORIES ──────────────────────────────────────────
insert into categories (slug, name, description, icon_name) values
  -- Core AI categories (original 10)
  ('ai-agents',              'AI Agents & Autonomous Agents',  'Tools that act autonomously to complete multi-step tasks.',            'Bot'),
  ('text-content',           'Text & Content Generation',       'AI writing assistants and content generators.',                       'FileText'),
  ('image-generation',       'Image Generation AI',             'Create stunning images from text prompts.',                           'Image'),
  ('video-generation',       'Video Generation AI',             'Generate and edit videos using AI.',                                  'Video'),
  ('ai-coding',              'Vibe Coding / AI Dev Tools',      'AI-powered coding assistants and developer tools.',                   'Code2'),
  ('seo-marketing',          'SEO & Marketing AI',              'Boost rankings and automate marketing with AI.',                      'TrendingUp'),
  ('voice-speech',           'Voice & Speech AI',               'Text-to-speech, voice cloning, and transcription tools.',            'Mic'),
  ('pdf-documents',          'PDF & Document AI',               'Summarize, chat with, and extract data from documents.',             'FileSearch'),
  ('meeting-transcription',  'Meeting & Transcription AI',      'Auto-transcribe calls and extract action items.',                    'ClipboardList'),
  ('workflow-automation',    'Workflow & Automation AI',        'Connect apps and automate repetitive tasks with AI.',                 'Zap'),
  -- Extended 30 categories
  ('data-analytics',         'Data & Analytics',                'AI tools for data analysis, visualization, and business intelligence.','BarChart2'),
  ('chatbot-builders',       'Chatbot Builders',                'Build custom AI chatbots and conversational agents without code.',    'MessageSquare'),
  ('research-summarization', 'Research & Summarization',        'AI tools for research, document summarization, and knowledge discovery.','BookOpen'),
  ('education-tutoring',     'Education & Tutoring',            'AI-powered learning, tutoring, flashcards, and educational tools.',  'GraduationCap'),
  ('graphic-design',         'Graphic Design',                  'AI design tools for logos, banners, brand assets, and visuals.',     'Palette'),
  ('music-audio',            'Music & Audio',                   'AI music generation, audio editing, mixing, and sound design tools.','Music'),
  ('social-media',           'Social Media AI',                 'AI tools for social media content creation and scheduling.',         'Share2'),
  ('email-outreach',         'Email & Outreach',                'AI email writing, cold outreach, and email marketing tools.',        'Mail'),
  ('translation',            'Translation AI',                  'AI-powered language translation, localization, and multilingual tools.','Languages'),
  ('presentations',          'Presentations & Slides',          'AI tools for creating presentations, pitch decks, and slide shows.', 'Presentation'),
  ('lead-generation',        'Lead Generation',                 'AI tools for finding, qualifying, and converting sales leads.',      'Target'),
  ('vision-ocr',             'Vision & OCR',                    'AI image recognition, optical character recognition, and computer vision.','ScanSearch'),
  ('health-wellness',        'Health & Wellness',               'AI tools for health tracking, fitness coaching, and mental wellness.','HeartPulse'),
  ('cybersecurity',          'Cybersecurity AI',                'AI-powered security scanning, threat detection, and protection.',    'ShieldCheck'),
  ('avatar-talking-head',    'Avatar & Talking Head',           'AI avatar creation, digital humans, and talking head video generation.','UserCircle'),
  ('developer-api',          'Developer & API Tools',           'AI APIs, SDKs, developer tools, and AI infrastructure platforms.',   'Cpu'),
  ('prediction-forecasting', 'Prediction & Forecasting',        'AI tools for demand forecasting, predictions, and business analytics.','LineChart'),
  ('sustainability-climate', 'Sustainability AI',               'AI tools for climate action, sustainability, and green tech.',       'Leaf'),
  ('gaming-interactive',     'Gaming & Interactive',            'AI tools for game development, NPCs, and interactive experiences.', 'Gamepad2'),
  ('personal-finance',       'Personal Finance',                'AI tools for budgeting, investing, and financial planning.',         'PiggyBank'),
  ('legal-ai',               'Legal AI',                        'AI tools for legal research, contract review, and compliance.',     'Scale'),
  ('hr-recruitment',         'HR & Recruitment',                'AI tools for hiring automation, resume screening, and HR management.','Users'),
  ('nonprofit-social',       'Nonprofit AI',                    'AI tools tailored for nonprofits and social impact organizations.', 'Heart'),
  ('customer-support',       'Customer Support',                'AI chatbots, helpdesk tools, and automated customer service.',      'Headphones'),
  ('knowledge-management',   'Knowledge Management',            'AI tools for wikis, knowledge bases, and documentation.',           'Brain'),
  ('ecommerce-product',      'E-commerce & Product',            'AI tools for online stores, product descriptions, and sales.',      'ShoppingBag'),
  ('podcast-audio',          'Podcast & Audio',                 'AI tools for podcast recording, editing, and distribution.',        'Podcast'),
  ('science-research',       'Science & Research',              'AI tools for scientific research, lab automation, and data.',       'FlaskConical'),
  ('photo-editing',          'Photo Editing',                   'AI-powered photo enhancement, background removal, and retouching.','ImagePlus'),
  ('video-editing',          'Video Editing AI',                'AI tools for video editing, color grading, subtitles, and effects.','FilmIcon')
on conflict (slug) do nothing;

-- ── TOOLS ─────────────────────────────────────────────────────
-- Helper: use the slugs we just inserted
with cat as (
  select id, slug from categories
)

insert into tools (
  slug, name, tagline, description,
  category_id, website_url, affiliate_url,
  is_free, free_tier_limits, pricing_detail,
  featured, tags, meta_title, meta_description
)
select v.slug, v.name, v.tagline, v.description,
       cat.id, v.website_url, v.affiliate_url,
       v.is_free, v.free_tier, v.pricing,
       v.featured, v.tags::text[], v.meta_title, v.meta_desc
from cat
join (values
  -- ── AI Agents (5) ────────────────────────────────────────
  ('ai-agents','agentgpt','AgentGPT','Run autonomous AI agents in your browser.','Deploy goal-driven AI agents that browse the web, write code, and execute multi-step plans—all from your browser with no setup required.','https://agentgpt.reworkd.ai',null,true,'5 agent runs/day','Free · Pro $40/mo',true,'{"ai-agent","autonomous","gpt"}','AgentGPT — Free Autonomous AI Agent in Browser','Run self-directed AI agents free in your browser. No code needed.'),
  ('ai-agents','autogpt','AutoGPT','Open-source autonomous AI agent framework.','The original open-source autonomous agent. AutoGPT chains GPT-4 tasks automatically to achieve long-horizon goals with file/web access.','https://autogpt.net',null,true,'Unlimited (self-host)','Free (open-source)',true,'{"autogpt","open-source","autonomous"}','AutoGPT — Free Open-Source Autonomous AI Agent','AutoGPT is the free open-source autonomous AI agent. Self-host unlimited.'),
  ('ai-agents','cognosys','Cognosys','Web-based AutoGPT with clean UI.','Cognosys provides a polished interface for running autonomous AI agents—set a goal, watch it research, plan, and execute tasks automatically.','https://cognosys.ai',null,true,'3 tasks/day','Free · Pro $10/mo',false,'{"cognosys","agent","ui"}','Cognosys — Free AI Agent with Clean Web UI','Run AI agents free with Cognosys. Clean interface, no setup needed.'),
  ('ai-agents','superagi','SuperAGI','Open-source autonomous AI agent platform.','SuperAGI lets you spawn, manage, and deploy autonomous agents with tool integrations, a GUI, and performance telemetry—fully self-hostable.','https://superagi.com',null,true,'Unlimited (self-host)','Free (open-source)',false,'{"superagi","open-source","platform"}','SuperAGI — Free Open-Source Autonomous Agent Platform','SuperAGI: free open-source platform for building autonomous AI agents.'),
  ('ai-agents','flowise','Flowise AI','Drag & drop LLM app builder.','Build LLM-powered chatbots and agents visually. Flowise provides a no-code drag-and-drop canvas for chaining AI tools and data sources.','https://flowiseai.com',null,true,'Unlimited (self-host)','Free (open-source)',false,'{"flowise","no-code","llm"}','Flowise AI — Free Drag-Drop LLM App Builder','Build AI agents visually with Flowise. Free and open-source.'),

  -- ── Text & Content (5) ────────────────────────────────────
  ('text-content','chatgpt','ChatGPT','The world-leading AI chatbot by OpenAI.','ChatGPT answers questions, writes essays, summarises documents, and codes—all in a conversational interface. Free tier uses GPT-3.5.','https://chat.openai.com',null,true,'Unlimited GPT-3.5','Free · Plus $20/mo',true,'{"chatgpt","openai","writing"}','ChatGPT Free — AI Writing & Chat by OpenAI','Use ChatGPT free for writing, research, and coding. No credit card needed.'),
  ('text-content','claude','Claude by Anthropic','Safe, helpful AI assistant by Anthropic.','Claude excels at nuanced writing, long-document analysis, and coding. The free tier on claude.ai gives access to Claude 3 Haiku.','https://claude.ai',null,true,'Unlimited Claude 3 Haiku','Free · Pro $20/mo',true,'{"claude","anthropic","writing"}','Claude Free — AI Assistant by Anthropic','Use Claude free for safe, accurate writing and analysis. No signup card needed.'),
  ('text-content','gemini','Google Gemini','Google''s multimodal AI assistant.','Gemini handles text, images, and code with Google-scale knowledge. Free on gemini.google.com with Gemini 1.5 Flash.','https://gemini.google.com',null,true,'Unlimited Gemini Flash','Free · Advanced $20/mo',true,'{"gemini","google","multimodal"}','Google Gemini Free — AI Writing & Image Understanding','Use Google Gemini free for writing, images, and code assistance.'),
  ('text-content','copy-ai','Copy.ai','AI copywriting for marketing teams.','Copy.ai generates ad copy, product descriptions, blog intros, and email sequences. Free tier includes 2,000 words per month.','https://copy.ai',null,true,'2,000 words/mo','Free · Pro $36/mo',false,'{"copywriting","marketing","ads"}','Copy.ai Free — AI Copywriting for Marketing','Generate marketing copy free with Copy.ai. 2,000 words/month included.'),
  ('text-content','rytr','Rytr','Affordable AI writer for blogs and emails.','Rytr produces blog posts, emails, product descriptions, and SEO meta in 30+ languages. Free tier: 10,000 characters per month.','https://rytr.me',null,true,'10,000 chars/mo','Free · Saver $9/mo',false,'{"rytr","blog","email"}','Rytr Free — AI Blog & Email Writer','Write blogs and emails free with Rytr. 10K characters/month on free plan.'),

  -- ── Image Generation (5) ──────────────────────────────────
  ('image-generation','midjourney','Midjourney','Photorealistic AI image generation.','Midjourney creates stunning photorealistic and artistic images from text prompts via Discord. Limited free trial available.','https://midjourney.com',null,false,null,'Basic $10/mo',true,'{"midjourney","image","art"}','Midjourney — Best AI Image Generator','Generate stunning AI images with Midjourney. Start free with a trial.'),
  ('image-generation','stable-diffusion','Stable Diffusion','Open-source AI image generator.','Stable Diffusion is the leading open-source image model. Run locally for free with ComfyUI or Automatic1111—no usage limits.','https://stability.ai',null,true,'Unlimited (self-host)','Free (open-source)',true,'{"stable-diffusion","open-source","local"}','Stable Diffusion Free — Open-Source AI Image Generator','Generate unlimited AI images free with Stable Diffusion locally.'),
  ('image-generation','dalle3','DALL·E 3','OpenAI''s best-in-class image model.','DALL·E 3 is integrated into ChatGPT (free tier gets limited generations) and the OpenAI API. Produces highly accurate prompt-following images.','https://openai.com/dall-e-3',null,true,'15 images/mo (ChatGPT free)','Free (via ChatGPT) · API pay-per-image',false,'{"dalle","openai","image"}','DALL·E 3 Free — AI Image Generation by OpenAI','Create AI images free with DALL·E 3 via ChatGPT. 15 images/month.'),
  ('image-generation','adobe-firefly','Adobe Firefly','Safe-for-commercial-use AI images.','Adobe Firefly is trained on licensed content, making outputs safe to use commercially. Free tier: 25 generative credits/month.','https://firefly.adobe.com',null,true,'25 credits/mo','Free · Premium $4.99/mo',false,'{"adobe","firefly","commercial"}','Adobe Firefly Free — Commercial-Safe AI Images','Generate commercial-safe AI images free with Adobe Firefly.'),
  ('image-generation','ideogram','Ideogram AI','Best AI for text inside images.','Ideogram specialises in generating images that contain accurate, readable text—a long-standing weakness of other models. Free tier available.','https://ideogram.ai',null,true,'25 images/day','Free · Plus $8/mo',false,'{"ideogram","text-in-image","design"}','Ideogram Free — AI Image Generator with Accurate Text','Generate AI images with real text using Ideogram. 25 free images/day.'),

  -- ── Video Generation (5) ──────────────────────────────────
  ('video-generation','runway','Runway ML','Professional AI video generation.','Runway Gen-3 Alpha creates cinematic AI videos from text or images. Includes motion brush, inpainting, and green screen tools.','https://runwayml.com',null,true,'125 credits free','Free · Standard $15/mo',true,'{"runway","video","gen3"}','Runway ML Free — AI Video Generation & Editing','Generate AI videos free with Runway. 125 credits on the free plan.'),
  ('video-generation','pika','Pika Labs','Text-to-video AI for creators.','Pika turns text prompts and images into short cinematic clips. Known for smooth motion and high visual quality. Free tier available.','https://pika.art',null,true,'250 credits/mo','Free · Basic $8/mo',false,'{"pika","text-to-video","creator"}','Pika Labs Free — AI Text to Video Generator','Create AI videos from text free with Pika. 250 credits/month included.'),
  ('video-generation','invideo-ai','InVideo AI','Script-to-video in minutes.','InVideo AI turns a text prompt or script into a fully edited video with voiceover, stock footage, and music—ready to publish.','https://invideo.io',null,true,'4 videos/week (watermarked)','Free · Plus $20/mo',false,'{"invideo","script-to-video","youtube"}','InVideo AI Free — Script to Video Generator','Turn scripts into videos free with InVideo AI. 4 videos/week on free plan.'),
  ('video-generation','kling','Kling AI','High-quality 1080p AI video generation.','Kling AI from Kuaishou generates up to 2-minute 1080p videos with realistic physics. 166 free credits per day on the free plan.','https://klingai.com',null,true,'166 credits/day','Free · Standard $10/mo',false,'{"kling","1080p","realistic"}','Kling AI Free — 1080p AI Video Generator','Generate 1080p AI videos free with Kling. 166 credits daily.'),
  ('video-generation','sora','Sora by OpenAI','OpenAI''s cinematic video generator.','Sora generates photorealistic videos up to 20 seconds from text. ChatGPT Plus users get access; limited free previews via OpenAI Labs.','https://sora.com',null,false,null,'Plus $20/mo',false,'{"sora","openai","cinematic"}','Sora OpenAI — AI Video Generator by OpenAI','Generate cinematic AI videos with Sora by OpenAI.'),

  -- ── AI Coding (5) ─────────────────────────────────────────
  ('ai-coding','github-copilot','GitHub Copilot','AI pair programmer inside VS Code.','GitHub Copilot autocompletes code, writes tests, explains errors, and suggests entire functions—right inside your editor.','https://github.com/features/copilot',null,true,'Free for students & OSS','Free (qualified) · Pro $10/mo',true,'{"copilot","github","vscode"}','GitHub Copilot Free — AI Code Autocomplete in VS Code','Code faster free with GitHub Copilot. Free for students and open-source.'),
  ('ai-coding','cursor','Cursor IDE','AI-first code editor built on VS Code.','Cursor is a VS Code fork with deep AI integration—multi-file edits, codebase chat, and instant refactors. Free tier: 2000 completions/month.','https://cursor.sh',null,true,'2,000 completions/mo','Free · Pro $20/mo',true,'{"cursor","ide","vscode"}','Cursor Free — AI Code Editor | VS Code Fork','Write code faster with Cursor AI IDE. 2,000 free AI completions/month.'),
  ('ai-coding','codeium','Codeium','Free AI autocomplete for 70+ languages.','Codeium provides unlimited AI code completions for 70+ languages in VS Code, JetBrains, Vim, and more—forever free for individuals.','https://codeium.com',null,true,'Unlimited (individuals)','Free · Teams $12/mo',false,'{"codeium","autocomplete","free"}','Codeium Free — Unlimited AI Code Autocomplete','Free unlimited AI code autocomplete in 70+ languages with Codeium.'),
  ('ai-coding','bolt-new','Bolt.new','Full-stack AI app builder in the browser.','Bolt.new scaffolds, runs, and deploys full-stack web apps from a text prompt—no local setup, instant preview, supports React, Vue, and more.','https://bolt.new',null,true,'1M tokens/day','Free · Pro $20/mo',false,'{"bolt","full-stack","no-code"}','Bolt.new Free — AI Full-Stack App Builder in Browser','Build full-stack apps free with Bolt.new. No setup, instant deploy.'),
  ('ai-coding','v0-dev','v0 by Vercel','AI UI component generator.','v0 generates React + Tailwind UI components from text prompts. Copy the JSX straight into your project. Free tier: 200 credits/month.','https://v0.dev',null,true,'200 credits/mo','Free · Plus $20/mo',false,'{"v0","vercel","ui"}','v0 by Vercel Free — AI React UI Component Generator','Generate React UI components free with v0 by Vercel. 200 credits/month.'),

  -- ── SEO & Marketing (5) ───────────────────────────────────
  ('seo-marketing','semrush-ai','Semrush AI','All-in-one SEO & content AI platform.','Semrush combines keyword research, backlink analysis, site audit, and AI content tools. Limited free account available.','https://semrush.com',null,true,'10 requests/day','Free (limited) · Pro $130/mo',false,'{"semrush","seo","keywords"}','Semrush Free — AI SEO & Keyword Research Tool','Research keywords and audit your site free with Semrush AI tools.'),
  ('seo-marketing','surfer-seo','Surfer SEO','AI content editor for top Google rankings.','Surfer SEO analyses the top-ranking pages and gives real-time NLP-based guidance to help your content rank. Trial available.','https://surferseo.com',null,false,null,'Essential $79/mo',false,'{"surfer","content","nlp"}','Surfer SEO — AI Content Optimisation for Google Rankings','Rank higher with Surfer SEO AI content editor. NLP-powered optimisation.'),
  ('seo-marketing','ahrefs','Ahrefs','Best backlink & keyword research tool.','Ahrefs provides backlink data, keyword explorer, site audit, and rank tracking. Free Webmaster Tools plan for site owners.','https://ahrefs.com',null,true,'Free Webmaster Tools','Free (limited) · Lite $99/mo',false,'{"ahrefs","backlinks","keywords"}','Ahrefs Free — Backlink & Keyword Research Tool','Analyse backlinks and keywords free with Ahrefs Webmaster Tools.'),
  ('seo-marketing','writesonic','Writesonic','AI writer with built-in SEO tools.','Writesonic generates SEO-optimised blog posts, landing pages, and ads. Free tier: 10,000 words per month across 100+ templates.','https://writesonic.com',null,true,'10,000 words/mo','Free · Small Team $19/mo',false,'{"writesonic","writing","seo"}','Writesonic Free — AI SEO Writer & Content Generator','Write SEO content free with Writesonic. 10,000 words/month included.'),
  ('seo-marketing','neuronwriter','NeuronWriter','NLP content optimisation for SEO.','NeuronWriter analyses SERP data and competitor content to give actionable NLP recommendations that push your articles to page one.','https://neuronwriter.com',null,false,null,'Bronze $19/mo',false,'{"neuronwriter","nlp","serp"}','NeuronWriter — AI NLP Content Optimiser for SEO','Optimise your content for Google rankings with NeuronWriter AI.'),

  -- ── Voice & Speech (5) ────────────────────────────────────
  ('voice-speech','elevenlabs','ElevenLabs','Most realistic AI voice generator.','ElevenLabs produces human-quality speech in 29 languages with voice cloning. Free tier: 10,000 characters/month.','https://elevenlabs.io',null,true,'10,000 chars/mo','Free · Starter $5/mo',true,'{"elevenlabs","tts","voice-clone"}','ElevenLabs Free — AI Voice Generator & Text to Speech','Generate realistic AI voices free with ElevenLabs. 10K chars/month.'),
  ('voice-speech','murf-ai','Murf AI','Professional voiceovers for videos.','Murf AI offers 120+ studio-quality AI voices for YouTube, ads, and e-learning. Free plan: 10 minutes of transcription.','https://murf.ai',null,true,'10 min transcription','Free · Basic $19/mo',false,'{"murf","voiceover","tts"}','Murf AI Free — AI Voiceover Generator for Videos','Create professional AI voiceovers free with Murf. 120+ voices.'),
  ('voice-speech','whisper','OpenAI Whisper','Open-source speech-to-text by OpenAI.','Whisper is OpenAI''s state-of-the-art ASR model—run locally for unlimited free transcription in 99 languages. Highly accurate.','https://openai.com/research/whisper',null,true,'Unlimited (local)','Free (open-source)',false,'{"whisper","transcription","asr"}','OpenAI Whisper Free — Open-Source Speech to Text','Transcribe audio free and offline with OpenAI Whisper. 99 languages.'),
  ('voice-speech','suno','Suno AI','Generate full songs with AI.','Suno creates complete songs—lyrics, melody, and vocals—from a text prompt. Free tier: 50 credits/day (~10 songs).','https://suno.ai',null,true,'50 credits/day','Free · Pro $8/mo',false,'{"suno","music","song"}','Suno AI Free — AI Song & Music Generator','Create full AI songs free with Suno. 50 credits (10 songs) daily.'),
  ('voice-speech','udio','Udio','High-quality AI music generation.','Udio generates radio-quality music tracks from text prompts across any genre. Free tier: 1,200 credits/month.','https://udio.com',null,true,'1,200 credits/mo','Free · Standard $10/mo',false,'{"udio","music","audio"}','Udio Free — AI Music Generator | Create Songs Free','Generate high-quality AI music free with Udio. 1,200 credits/month.'),

  -- ── PDF & Documents (5) ───────────────────────────────────
  ('pdf-documents','chatpdf','ChatPDF','Chat with any PDF document.','Upload a PDF and ask questions about it in plain English. ChatPDF extracts, summarises, and explains your documents instantly.','https://chatpdf.com',null,true,'3 PDFs/day, 50 pages each','Free · Plus $5/mo',true,'{"chatpdf","pdf","summarise"}','ChatPDF Free — Chat With Any PDF Document','Upload and chat with PDFs free using ChatPDF. 3 documents/day.'),
  ('pdf-documents','pdf-ai','PDF.ai','AI PDF reader and summariser.','PDF.ai lets you upload multiple PDFs and ask cross-document questions. Free tier: 1 PDF at a time, unlimited questions.','https://pdf.ai',null,true,'1 PDF at a time','Free · Pro $14/mo',false,'{"pdf-ai","documents","qa"}','PDF.ai Free — AI PDF Reader & Question Answering','Ask questions about PDFs free with PDF.ai. Upload and chat instantly.'),
  ('pdf-documents','humata','Humata AI','Research paper AI assistant.','Humata reads academic papers and legal documents, then answers detailed questions with citations. Free: 60 pages/month.','https://humata.ai',null,true,'60 pages/mo','Free · Student $1.99/mo',false,'{"humata","research","academic"}','Humata AI Free — Chat With Research Papers & PDFs','Understand research papers instantly with Humata AI. 60 pages free/month.'),
  ('pdf-documents','doctranslate','DocTranslate','AI document translation tool.','DocTranslate translates PDFs, Word files, and PowerPoints while preserving the original formatting. Free: 2 files/day.','https://doctranslate.io',null,true,'2 files/day','Free · Basic $8/mo',false,'{"doctranslate","translation","pdf"}','DocTranslate Free — AI Document Translation Tool','Translate PDFs and docs free with DocTranslate. Format preserved.'),
  ('pdf-documents','smallpdf','SmallPDF AI','All-in-one PDF toolkit with AI.','SmallPDF provides 21 PDF tools—compress, convert, merge, e-sign—plus an AI assistant for summarisation. Free: 2 tasks/hour.','https://smallpdf.com',null,true,'2 tasks/hour','Free · Pro $9/mo',false,'{"smallpdf","compress","convert"}','SmallPDF Free — AI PDF Tools: Compress, Convert, Merge','Use 21 PDF tools free with SmallPDF AI. Compress, convert, and more.'),

  -- ── Meeting Transcription (5) ─────────────────────────────
  ('meeting-transcription','otter-ai','Otter.ai','Real-time meeting transcription AI.','Otter.ai auto-joins Zoom, Teams, and Meet calls to transcribe, summarise, and extract action items in real time. Free: 300 min/month.','https://otter.ai',null,true,'300 min/mo','Free · Pro $17/mo',true,'{"otter","transcription","meetings"}','Otter.ai Free — AI Meeting Transcription & Notes','Transcribe Zoom and Teams meetings free with Otter.ai. 300 min/month.'),
  ('meeting-transcription','fireflies','Fireflies.ai','AI notetaker for every meeting.','Fireflies joins your video calls, records, transcribes, and surfaces searchable meeting intelligence across 100+ integrations.','https://fireflies.ai',null,true,'800 min storage','Free · Pro $18/mo',false,'{"fireflies","notetaker","zoom"}','Fireflies.ai Free — AI Meeting Notetaker & Transcription','Auto-transcribe meetings free with Fireflies.ai. 800 minutes storage.'),
  ('meeting-transcription','tl-dv','tl;dv','Record, transcribe, and clip meetings.','tl;dv records Zoom and Google Meet, timestamps key moments, and lets you share clips. Free plan: unlimited recordings.','https://tldv.io',null,true,'Unlimited recordings','Free · Pro $18/mo',false,'{"tldv","recording","clips"}','tl;dv Free — AI Meeting Recorder & Clip Creator','Record and transcribe unlimited meetings free with tl;dv.'),
  ('meeting-transcription','notta','Notta AI','Multilingual meeting transcription.','Notta transcribes meetings in 58 languages with speaker identification. Free: 120 minutes of transcription per month.','https://notta.ai',null,true,'120 min/mo','Free · Pro $14/mo',false,'{"notta","multilingual","transcription"}','Notta AI Free — Multilingual Meeting Transcription','Transcribe meetings in 58 languages free with Notta AI.'),
  ('meeting-transcription','fathom','Fathom AI','Free AI meeting notetaker for Zoom.','Fathom records, transcribes, and highlights your Zoom calls—completely free. Unlimited recordings with AI summaries and CRM sync.','https://fathom.video',null,true,'Unlimited (Zoom)','Free · Team $19/mo',false,'{"fathom","zoom","notetaker"}','Fathom AI Free — Unlimited Zoom Meeting Notetaker','Get unlimited free Zoom transcription and AI notes with Fathom.'),

  -- ── Workflow & Automation (5) ─────────────────────────────
  ('workflow-automation','zapier','Zapier','Connect 6,000+ apps with AI automation.','Zapier automates workflows between 6,000+ apps with triggers, actions, and AI steps. Free: 100 tasks/month.','https://zapier.com',null,true,'100 tasks/mo','Free · Starter $20/mo',true,'{"zapier","automation","integrations"}','Zapier Free — AI Workflow Automation | 6,000+ App Integrations','Automate workflows between 6,000+ apps free with Zapier. 100 tasks/month.'),
  ('workflow-automation','make','Make (Integromat)','Visual workflow automation platform.','Make (formerly Integromat) offers a visual drag-and-drop workflow builder with 1,500+ app integrations. Free: 1,000 ops/month.','https://make.com',null,true,'1,000 ops/mo','Free · Core $9/mo',false,'{"make","integromat","visual"}','Make Free — Visual Workflow Automation Platform','Build visual automations free with Make. 1,000 operations/month.'),
  ('workflow-automation','n8n','n8n','Open-source workflow automation.','n8n is a self-hostable workflow automation tool with 400+ integrations and AI nodes. Run locally for unlimited free automations.','https://n8n.io',null,true,'Unlimited (self-host)','Free (OSS) · Cloud $24/mo',false,'{"n8n","open-source","self-host"}','n8n Free — Open-Source Workflow Automation','Automate unlimited workflows free with n8n. Self-host with no limits.'),
  ('workflow-automation','activepieces','Activepieces','Open-source Zapier alternative.','Activepieces is a modern open-source automation tool. Self-host for free or use the cloud. 100+ integrations with AI flow steps built in.','https://activepieces.com',null,true,'Unlimited (self-host)','Free (OSS) · Cloud $9/mo',false,'{"activepieces","open-source","zapier-alt"}','Activepieces Free — Open-Source Zapier Alternative','Automate apps free with Activepieces. Open-source Zapier alternative.'),
  ('workflow-automation','bardeen','Bardeen AI','Browser automation with AI.','Bardeen automates browser tasks—scraping, form-filling, and data transfer—using natural language commands. Free: 1 automation/day.','https://bardeen.ai',null,true,'1 automation/day','Free · Pro $10/mo',false,'{"bardeen","browser","scraping"}','Bardeen AI Free — Browser Automation with AI Commands','Automate browser tasks free with Bardeen AI. Natural language commands.')
) as v(cat_slug, slug, name, tagline, description, website_url, affiliate_url,
       is_free, free_tier, pricing, featured, tags, meta_title, meta_desc)
on (cat.slug = v.cat_slug)
on conflict (slug) do nothing;
